CREATE OR REPLACE ALGORITHM=MERGE VIEW form_create_project_view AS
select  
  `id` AS 'id', -- '编号',
  `apply_id` AS 'applyId', --  '申请人id',
  get_user_name(apply_id) AS 'applyUserName', 
  `apply_date` AS 'applyDate', --  '申请时间',
  `project_type` AS 'projectType', --  '项目类型',
  `project_name` AS 'projectName', --  '项目名称',
  CONCAT_WS('',project_number,'-L',level) AS 'projectNumber', --  '项目编号',
  `is_create_project` AS 'isCreateProject', --  '是否为创新类项目',
  `is_replace_project` AS 'isReplaceProject', --  '是否为替代类项目',
  `sponsor_ids` AS 'sponsorIds', --  'Sponsor',
  `sponsor_names` AS 'sponsorNames', --  'Sponsor',
  `leader_ids` AS 'leaderIds', --  'Leader',
  `leader_names` AS 'leaderNames', --  'Leader',
  `project_sponsor_type` AS 'projectSponsorType', --  '项目发起分类',
  `acs_number` AS 'acsNumber', --  'ACS编号',
  `fixed_assets` AS 'fixedAssets', --  '是否固定资产',
  `client_year_demanded` AS 'clientYearDemanded', --  '客户年需求量',
  `client_year_demanded_amount` AS 'clientYearDemandedAmount', --  '客户年需求金额',
  `client_year_demanded_unit` AS 'clientYearDemandedUnit', --  '单位',
  `my_portion` AS 'myPortion', --  '我司的份额（%）',
  `competitor_situation` AS 'competitorSituation', --  '竞争对手情况',
  `year_saleroom` AS 'yearSaleroom', --  '年销售额',
  `we_opportunity` AS 'weOpportunity', --  '我们的机会%',
  `gcm` AS 'gcm', --  'GCM',
  `sample_cost_input` AS 'sampleCostInput', --  '样品费用投入',
  `fixed_assets_input` AS 'fixedAssetsInput', --  '固定资产投入',
  `advantage` AS 'advantage', --  '优势',
  `project_involve_guest` AS 'projectInvolveGuest', --  '项目涉及的客户',
  `project_involve_guest_id` AS 'projectInvolveGuestId', --  '客户的id',
  `project_involve_guest_number` AS 'projectInvolveGuestNumber', --  '客户的编码',
  `technology_difficulty` AS 'technologyDifficulty', --  '技术难点',
  `product_construction` AS 'productConstruction', --  '对应的产品结构',
  `business_target` AS 'businessTarget', --  '商务方面',
  `level` AS 'level', --  'level等级',
  (CASE level WHEN '1' THEN 'level1现有结构和应用' WHEN '2' THEN 'level2现有结构材料厚度变化,或新应用' WHEN '3' THEN 'level3现有材料组合的新结构,或新原材料' WHEN '4' THEN 'level4新材料开发的新结构,或新设备、新技术的开发' ELSE '' END) AS `levelValue`, -- LEVEL等级——中文
  `project_start_time` AS 'projectStartTime', --  '项目开始时间',
  `project_verify_time` AS 'projectVerifyTime', --  '项目验证时间',
  `business_order_time` AS 'businessOrderTime', --  '商务订单时间',
  `project_finish_time` AS 'projectFinishTime', --  '项目完成时间',
  `research_principal_ids` AS 'researchPrincipalIds', --  '研发负责人',
  `research_principal_names` AS 'researchPrincipalNames', --  '研发负责人',
  `sell_principal_ids` AS 'sellPrincipalIds', --  '销售负责人',
  `sell_principal_names` AS 'sellPrincipalNames', --  '销售负责人',
  `team_participant_ids` AS 'teamParticipantIds', --  '团队其他成员',
  `team_participant_names` AS 'teamParticipantNames', --  '团队其他成员',
  create_date AS 'createDate',
  create_by AS 'createById',
  get_user_name(create_by) AS 'createByName',
  update_by AS 'updateById',
  update_date AS 'updateDate',
  get_user_name(update_by) AS 'updateByName',
  `office_id` AS 'officeId', --  '归属公司',
  get_company_code(office_id ) AS 'officeCode' , -- '公司编号'
  get_company_name(office_id ) AS 'officeName'  ,	-- '公司名称'
  `remarks` AS 'remarks', --  '备注信息',
  `del_flag` AS 'delFlag', --  '删除标记',
  `serial_number` AS 'serialNumber', --  '流水号',
--  `flow_status` AS 'flowStatus', --  '表单状态',
  (CASE flow_status WHEN 'create' THEN '已创建' WHEN 'submit' THEN '已提交' WHEN 'approving' THEN '审批中' WHEN 'finish' THEN '已完成' ELSE '' END) AS `flowStatus`,
  `flow_id` AS 'flowId', --  '流程id',
  `only_sign` AS 'onlySign', --  '标识一组审批记录',
  `if_new_type` AS 'ifNewType', --  '是否新型',
  `termination_status` AS 'terminationStatus', --  '操作状态：终止、放开修改。。。',
  get_current_operator(id) currentOperator	-- '当前审批人'	
 from `form_create_project` where del_flag=0
 
 
 
 
 